name: Build and Deploy Cocos Project

on:
  push:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    # Uncomment if you want to build the project
    # - name: Build Project
    #   run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build  

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Checkout dev branch
      uses: actions/checkout@v3
      with:
        ref: dev
        path: dev

    - name: Configure Git user
      run: |
        git config user.name "prathm"
        git config user.email "prathm@example.com"

    - name: Forcefully remove and update build folder
      run: |
        rm -rf build/
        cp -r dev/build build/
        git add -f build/
        git commit -m "Update build folder from dev"
        git push origin main
