name: Build Cocos Project

on:
  push:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    # - name: Build Project
    #   run: npm run build

    - name: Checkout or create main branch
      run: |
        git fetch origin main
        git checkout main || git checkout -b main

    - name: Configure Git user
      run: |
        git config user.name "prathm"
        git config user.email "prathm@github.com"

    - name: Merge dev into main
      run: |
        git merge dev --allow-unrelated-histories --no-ff -m "Merge dev into main"
        git push origin main
