name: CI/CD Pipeline

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: npm install

      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main

      - name: Merge dev into main
        run: |
          git merge dev --allow-unrelated-histories --no-ff -m "Merge dev into main"
          git push origin main
