name: CI/CD Pipeline

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'  

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build:webgl  

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Copy build output and commit changes
        run: |
          # Copy build artifacts from the build job
          cp -r ../build/* .
          git add .
          git commit -m "Deploy build artifacts to main branch"
          git push origin main
