name: CI/CD Pipeline

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Push changes to main branch
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
            branch: main
            folder: Cocos-Platform
